name: "Ferme les vieux bugs"
on:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Ce bug a été fermé pour cause d''une trop longue inactivité' 