name: 'Workflow dispatch'
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Nom de la première personne'
        required: true
      param2:
        description: 'Nom de la seconde personne'
        required: false
        default: 'Anonymouse'


jobs:
  input-message:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Dit bonjour à ${{ github.event.inputs.param1 }} et ${{ github.event.inputs.param2 }} !"
